pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [lemastero]
      label:
        add: [dependency-update]
  - name: merge Scala Steward's PRs
    conditions:
      - base=main
      - author=scala-steward
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
